Update cmake-multi-platform.yml

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -1,5 +1,3 @@
-# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
-# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
 name: CMake on multiple platforms
 
 on:
@@ -13,15 +11,8 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     strategy:
-      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
-      fail-fast: false
+      fail-fast: true
 
-      # Set up a matrix to run the following 3 configurations:
-      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
-      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
-      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
-      #
-      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
       matrix:
         os: [ubuntu-latest, windows-latest]
         build_type: [Release]
@@ -50,28 +41,91 @@ jobs:
         submodules: recursive
 
     - name: Set reusable strings
-      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
       id: strings
       shell: bash
       run: |
         echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
 
     - name: Configure CMake
-      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
-      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
       run: >
         cmake -B ${{ steps.strings.outputs.build-output-dir }}
         -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
         -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
         -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
+        -DPI_THREADPOOL_BUILD_TESTS=ON
         -S ${{ github.workspace }}
 
     - name: Build
-      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
       run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
 
     - name: Test
       working-directory: ${{ steps.strings.outputs.build-output-dir }}
-      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
-      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
       run: ctest --build-config ${{ matrix.build_type }}
+  # FreeBSD build using vmactions/freebsd-vm@v1
+  build-freebsd:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Build & Test on FreeBSD
+        uses: vmactions/freebsd-vm@v1
+        with:
+          release: "13.4"
+          usesh: true
+
+          prepare: |
+            pkg update -f
+            pkg install -y cmake ninja llvm16
+
+          run: |
+            export PATH="/usr/local/llvm16/bin:$PATH"
+            
+            which clang-scan-deps || (echo "clang-scan-deps not found!" && exit 1)
+            
+            mkdir -p build
+            cmake -B build -G Ninja \
+                  -DCMAKE_C_COMPILER=cc \
+                  -DCMAKE_CXX_COMPILER=c++ \
+                  -DCMAKE_BUILD_TYPE=Release \
+                  -DPI_THREADPOOL_BUILD_TESTS=ON \
+                  .
+            cmake --build build
+            cd build
+            ctest --output-on-failure
+
+  # OpenBSD build using vmactions/openbsd-vm@v1
+  build-openbsd:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Build & Test on OpenBSD
+        uses: vmactions/openbsd-vm@v1
+        with:
+          release: "7.6"
+          usesh: true
+
+          prepare: |
+            export PKG_PATH="https://cdn.openbsd.org/pub/OpenBSD/7.6/packages/amd64/"
+            
+            pkg_add -I cmake-3.30.1v1 ninja-1.11.1p0v0 llvm-16.0.6p30
+
+          run: |
+            export PATH="/usr/local/llvm/bin:$PATH"
+            
+            which clang-scan-deps || (echo "clang-scan-deps not found!" && exit 1)
+            
+            mkdir -p build
+            cmake -B build -G Ninja \
+                  -DCMAKE_C_COMPILER=cc \
+                  -DCMAKE_CXX_COMPILER=c++ \
+                  -DCMAKE_BUILD_TYPE=Release \
+                  -DPI_THREADPOOL_BUILD_TESTS=ON \
+                  .
+            cmake --build build
+            cd build
+            ctest --output-on-failure
